table = [
"64 64 199 2 ",
"   c None",
".  c #DE2C2C",
"X  c #DF2C2C",
"o  c #D83738",
"O  c #E33332",
"+  c #D43D40",
"@  c #B9484D",
"#  c #B34C52",
"$  c #AA525A",
"%  c #916671",
"&  c #BA7179",
"*  c #DF4949",
"=  c #DF4B4B",
"-  c #E75D5F",
";  c #F75251",
":  c #F95554",
">  c #FA5655",
",  c #F95756",
"<  c #C36D73",
"1  c #C46D73",
"2  c #717D8E",
"3  c #707E8E",
"4  c #717E8E",
"5  c #3FA3BB",
"6  c #668597",
"7  c #62889B",
"8  c #608A9D",
"9  c #7C8D9D",
"0  c #5D9CB0",
"q  c #44A7BF",
"w  c #50A2B8",
"e  c #3CABC4",
"r  c #2BB3CE",
"t  c #2DB2CD",
"y  c #27B5D1",
"u  c #25B7D3",
"i  c #26B7D3",
"p  c #27B7D3",
"a  c #28B4D0",
"s  c #28B7D3",
"d  c #28B8D3",
"f  c #29B8D3",
"g  c #2EB9D3",
"h  c #2FB9D3",
"j  c #2CB9D4",
"k  c #2FB9D4",
"l  c #30B9D4",
"z  c #33BAD4",
"x  c #32BBD5",
"c  c #33BBD5",
"v  c #34BAD4",
"b  c #36BBD4",
"n  c #37BCD6",
"m  c #39BBD4",
"M  c #3BBCD5",
"N  c #3BBED7",
"B  c #3CBCD5",
"V  c #3EBFD7",
"C  c #46BED6",
"Z  c #46BFD6",
"A  c #47BFD6",
"S  c #48BFD6",
"D  c #49BFD6",
"F  c #43C0D8",
"G  c #47C2D9",
"H  c #4FC4DB",
"J  c #50C1D7",
"K  c #54C2D7",
"L  c #56C2D7",
"P  c #57C2D7",
"I  c #58C3D7",
"U  c #51C5DB",
"Y  c #52C5DB",
"T  c #53C6DB",
"R  c #5CC9DD",
"E  c #5FC9DE",
"W  c #60C5D8",
"Q  c #61C5D8",
"!  c #65C6D9",
"~  c #66C6D9",
"^  c #67C6D9",
"/  c #69C7D9",
"(  c #6BC7D9",
")  c #62CADE",
"_  c #64CBDF",
"`  c #66CCDF",
"'  c #6EC8DA",
"]  c #6FC8DA",
"[  c #73C9DA",
"{  c #75CADA",
"}  c #76CADA",
"|  c #79CBDB",
" . c #7ECCDB",
".. c #72D0E2",
"X. c #74D0E2",
"o. c #75D1E2",
"O. c #77D1E3",
"+. c #78D2E3",
"@. c #79D2E3",
"#. c #7DD3E4",
"$. c #7ED4E4",
"%. c #818C9B",
"&. c #CC8B90",
"*. c #E58384",
"=. c #E88585",
"-. c #FB9C9B",
";. c #F9A4A3",
":. c #E9B3B3",
">. c #E9B5B5",
",. c #84CDDC",
"<. c #89CEDC",
"1. c #8ACFDC",
"2. c #8BCFDC",
"3. c #8CCFDC",
"4. c #8FD0DD",
"5. c #90D0DD",
"6. c #92D0DD",
"7. c #92D1DD",
"8. c #93D1DD",
"9. c #95D1DD",
"0. c #96D2DD",
"q. c #9AD2DE",
"w. c #9CD3DE",
"e. c #9DD3DE",
"r. c #9ED4DE",
"t. c #ABD6DF",
"y. c #ACD7DF",
"u. c #85D6E5",
"i. c #86D6E6",
"p. c #8AD7E7",
"a. c #8DD8E7",
"s. c #9DD6E1",
"d. c #92DAE8",
"f. c #97DCE9",
"g. c #99DDEA",
"h. c #9DDEEA",
"j. c #9FDEEB",
"k. c #9FDFEB",
"l. c #A2DAE5",
"z. c #A1DFEB",
"x. c #B0D8E0",
"c. c #B3D8E0",
"v. c #BBDAE1",
"b. c #A4E0EC",
"n. c #A5E1EC",
"m. c #A6E1EC",
"M. c #A8E1EC",
"N. c #ABE3ED",
"B. c #B1E4EE",
"V. c #B2E5EF",
"C. c #B4E5EF",
"Z. c #B8E7F0",
"A. c #BAE8F0",
"S. c #E1D1D2",
"D. c #E1D2D3",
"F. c #C4DCE2",
"G. c #C4DDE2",
"H. c #C5DDE2",
"J. c #D0DFE3",
"K. c #D2E0E3",
"L. c #D5E1E3",
"P. c #DBE2E4",
"I. c #DCE2E4",
"U. c #DDE2E4",
"Y. c #DDE3E4",
"T. c #DFE3E4",
"R. c #DFEBEE",
"E. c #C5EBF2",
"W. c #C6EBF3",
"Q. c #C8ECF3",
"!. c #CCEDF4",
"~. c #D6F0F6",
"^. c #D9F2F6",
"/. c #DEF3F7",
"(. c #E0E3E4",
"). c #E1E3E4",
"_. c #E1E4E5",
"`. c #E2E4E5",
"'. c #E6E8E9",
"]. c #EEEFEF",
"[. c #EEEFF0",
"{. c #E0F4F8",
"}. c #E2F5F8",
"|. c #EDF8FB",
" X c #EFF9FB",
".X c #F5F6F6",
"XX c #F6F6F6",
"oX c #F3FAFC",
"OX c #F7FCFD",
"+X c #F9FCFD",
"@X c #FAFDFD",
"#X c #FBFDFE",
"$X c gray99",
"%X c #FEFDFD",
"&X c #FCFEFE",
"*X c #FDFEFE",
"=X c #FEFEFE",
"-X c #FEFFFF",
";X c white",

"                                                    u u u u u u u u u u u u                                                     ",
"                                            u u u u u u u u u u u u u u u u u u u u                                             ",
"                                        u u u u u u u u u u u u u u u u u u u u u u u u                                         ",
"                                  u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u                                   ",
"                                u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u                                 ",
"                            u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u                             ",
"                          u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u                           ",
"                      u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u                       ",
"                    u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u                     ",
"                  u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u                   ",
"                u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u                 ",
"              u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u               ",
"              u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u               ",
"            u u u u u u u u u u u u j ..j.N.j.O.b u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u             ",
"          u u u u u u u u u u u u u u b.;X;X;X;X@Xb.z u u u u u u u u u u u u u u u u u u u u E g.u u u u u u u u u u           ",
"          u u u u u u u u u u u u u u u b.;X;X;X;X;X/.Z u u u u u u u u u u u u u u u u u T E.;X;Xs.u u u u u u u u u           ",
"        u u u u u u u u u u u u u u u u u b.;X;X;X;X;X{.z u u u u u u u u u u u u u u G Z.;X;X$X'.v.u u u u u u u u u u         ",
"      u u u u u u u u u u u u u u u u u u u b.;X;X;X;X;XM.u u u u u u u u u u u u B N.;X;X;X$X'.).L u u u u u u u u u u u       ",
"      u u u u u u u u u u f u u u u u u u u u b.;X;X;X;X@XN u u u u u u u u u u u A.;X;X;X$X'.).t.u u u u u u u u u u u u       ",
"      u u u u u u u u u u ! 4.u u u u u u u u u m.;X;X;X;X$.u u u u u u u u u u u ^.;X;X$X'.).T.C u u u u u u u u u u u u       ",
"    u u u u u u u u u u u <.`.4.u u u u u u u u T ;X;X;X;Xz.u u u u u u u u u u s OX;X;X'.`.`.r.u u u u u u u u u u u u u u     ",
"    u u u u u u u u u u u 0.`.`.4.u u u u u u u T ;X;X;X;XB.u u u u u u u u u s C.;X$X'.`.`.U.N u u u u u u u u u u u u u u     ",
"  u u u u u u u u u u u u <.`.`.`.4.u u u u u u T ;X;X;X;Xm.u u u u u u u u s V.;X$X'.).`.`.<.u u u u u u u u u u u u u u u u   ",
"  u u u u u u u u u u u u ( `.`.`.`.4.u u u u u j.;X;X;X;X$.u u u u u u u s C.;X$X'.U.[ S z u u u u u u u u u u u u u u u u u   ",
"  u u u u u u u u u u u u z P.`.`.`.`.5.S S S <.[.;X;X;X;Xd.u u u u u u s C.;X$X'.U.W u u u u u u u u u u u u u u u u u u u u   ",
"  u u u u u u u u u u u u u 4.`.`.`.`.`.`.`.`.`.`.[.;X;X;X;Xp.u u u u s C.;X$X'.U.W u u u u u u u u u u u u u u u u u u u u u   ",
"u u u u u u u u u u u u u u h G.`.`.`.`.`.`.`.`.`.`.[.;X;X;X;Xp.u u s C.;X$X'.U.W u u u u u u u u u u u u u u u u u u u u u u u ",
"u u u u u u u u u u u u u u u B G.`.`.`.`.`.`.`.`.`.`.[.;X;X;X;Xp.s C.;X$X'.U.W u u u u u u u u u u u u u u u u u u u u u u u u ",
"u u u u u u u u u u u u u u u u k 5.U.`.`.`.`.`.`.`.`.`.[.;X;X;X;X~.;X$X'.U.W u u u u u u u u u u u u u u u u u u u u u u u u u ",
"u u u u u u u u u u u u u u u u u u b ] 5.r.5.[  .).`.`.`.[.;X;X;X;X$X'.U.W u u u u u u u u u u u u u u u u u u u u u u u u u u ",
"u u u u u u u u u u u u u u u u u u u u u u u u u } ).`.`.>.;.;X;X$X'.U.W u u u u u u u u u u u u u u u u u u u u u u u u u u u ",
"u u u u u u u u u u u u u u u u u u u u u u u u u u } ).:., , -.$X'.)..Xp.u u u u u u u u u u u u u u u u u u u u u u u u u u u ",
"u u u u u u u u u u u u u u u u u u u u u u u u t 9 %.&., , , ; *.)..X;X;Xp.u u u u u u u u u u u u u u u u u u u u u u u u u u ",
"u u u u u u u u u u u u u u u u u u u u u u u t 1 > > > > , ; O X =.;X;X;X;Xp.u u u u u u u u u u u u u u u u u u u u u u u u u ",
"u u u u u u u u u u u u u u u u u u u u u u t 1 , , > > > ; O X X * ].;X;X;X;Xp.u u u u u u u u u u u u u u u u u u u u u u u u ",
"u u u u u u u u u u u u u u u u u u u u u t 1 > > > > > ; O X X * S.).[.;X;X;X;Xp.u u u u u u u u u u u u u u u u u u u u u u u ",
"u u u u u u u u u u u u u u u u u u u u t 1 > > > > > ; O X X o S.`.`.`.].;X;X;X;Xa.E ..` N u u u u u u u u u u u u u u u u u u ",
"u u u u u u u u u u u u u u u u u u u t 1 > > > > > ; O X X X $ | ).`.).).].;X;X;X;X;X;X;X;XE.T u u u u u u u u u u u u u u u u ",
"  u u u u u u u u u u u u u u u u u t 1 > > > > > ; O X X X X # u } ).).).).].;X;X;X;X;X;X;X;X@X+.u u u u u u u u u u u u u u   ",
"  u u u u u u u u u u u u u u u u t 1 > > > > > ; O X X X X . 6 u u } ).).).).].;X;X!./.;X;X;X;X;X) u u u u u u u u u u u u u   ",
"  u u u u u u u u u u u u u u u t 1 > > > > > ; O X X X X . 2 u u u u } ).`.`.`.[.V.u u B @.Q.;X;X}.f u u u u u u u u u u u u   ",
"  u u u u u u u u u u u u u u t 1 > > > > > ; O X X X X . 2 u u u u u u | ).`.`.q.u u u u u H ;X;X;X_ u u u u u u u u u u u u   ",
"    u u u u u u u u u u u u t 1 > > > > > ; O X X X . . 2 u u u u u u u H ).`.c.u u u u u u u  X;X;Xg.u u u u u u u u u u u     ",
"    u u u u u u u u u u u r 1 , > > > > ; O X X . . . 2 u u u u u u u u W `.`.F.u u u u u u u C.;X;XN.u u u u u u u u u u u     ",
"      u u u u u u u u u u 0 > > > > > ; O X X X . . 2 u u u u u u u u u I `.`.).m u u u u u u u.;X;Xz.u u u u u u u u u u       ",
"      u u u u u u u u u u q : > > > ; O X X X X . 2 u u u u u u u u u u b ).`.`.( u u u u u H  X;X;XO.u u u u u u u u u u       ",
"      u u u u u u u u u u u & > > ; O X X X X X 2 u u u u u u u u u u u u x.`.`.c.C u u u C R.;X;XoXz u u u u u u u u u u       ",
"        u u u u u u u u u u e - ; O X X X X X 2 u u u u u u u u u u u u u C U.`.`.`.J.r.} K.`.[.;Xu.u u u u u u u u u u         ",
"          u u u u u u u u u u w o . . . . . 2 u u u u u u u u u u u u u u u ( U.`.`.`.`.`.`.`.`.l.u u u u u u u u u u           ",
"          u u u u u u u u u u u q @ . . . 2 u u u u u u u u u u u u u u u u u L G.`.`.`.`.`.L.} u u u u u u u u u u u           ",
"            u u u u u u u u u u u u 7 % 8 u u u u u u u u u u u u u u u u u u u u L ,.0.3.! h u u u u u u u u u u u             ",
"              u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u               ",
"              u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u               ",
"                u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u                 ",
"                  u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u                   ",
"                    u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u                     ",
"                      u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u                       ",
"                          u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u                           ",
"                            u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u                             ",
"                                u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u                                 ",
"                                  u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u                                   ",
"                                        u u u u u u u u u u u u u u u u u u u u u u u u                                         ",
"                                            u u u u u u u u u u u u u u u u u u u u                                             ",
"                                                    u u u u u u u u u u u u                                                     "
]