table = [
"48 48 44 1 ",
"  c None",
". c #E64919",
"X c #E64A19",
"o c #E64A1A",
"O c #E75122",
"+ c #E75324",
"@ c #E85C30",
"# c #E95E32",
"$ c #E96137",
"% c #EB6B42",
"& c #EB6E47",
"* c #EC7651",
"= c #ED7F5C",
"- c #FF8A65",
"; c #FF8C68",
": c #F09275",
"> c #FF9472",
", c #F19B80",
"< c #F19C81",
"1 c #F19C82",
"2 c #F3A890",
"3 c #F3AA93",
"4 c #F4B09B",
"5 c #FDB39C",
"6 c #FDB39D",
"7 c #F6BEAC",
"8 c #F6C1B0",
"9 c #FCD4CA",
"0 c #FCD5CB",
"q c #FCD7CF",
"w c #FADAD0",
"e c #FBE3DB",
"r c #FBE4E0",
"t c #FBE4E1",
"y c #FBE5E1",
"u c #FCE8E1",
"i c #FBE9E7",
"p c #FDEEE9",
"a c #FDEFEA",
"s c #FEF5F2",
"d c #FEF9F7",
"f c #FEFBFA",
"g c #FFFDFC",
"h c white",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                          o                     ",
"                     .XXXXX                     ",
"               XXXXXXXXXXXX                     ",
"          XXXXXXXXXXXXXXXXX                     ",
"      XXXXXXXXXXXXXXXXXXXXX---------------      ",
"      XXXXXXXXXXXXXXXXXXXXX---------------      ",
"      XXXXXXXXXXXXXXXXXXXXX---------------      ",
"      XXXXXXXXXXXXXXXXXXXXX-----y06;------      ",
"      XXXXXXXXXXXXXXXXXXXXX-----iiiq>-----      ",
"      XXXXXXXXXXXXXXXXXXXXX60y--iiiiq;----      ",
"      XXXXXXXXXXXXXXXXXXXXXiii--iiiii5----      ",
"      XXXXXXhhhhhde4@XXXXXXiii--iiiii9----      ",
"      XXXXXXhhhhhhhha$XXXXXiii--iiiiit----      ",
"      XXXXXXhhh:,8ghh7XXXXXiii------------      ",
"      XXXXXXhhhXXX3hhaXXXXXiii------------      ",
"      XXXXXXhhhXXX=hhfXXXXXiiiiiiiir------      ",
"      XXXXXXhhhXXX<hhuXXXXXiiiiiiii9------      ",
"      XXXXXXhhh&*1shh3XXXXXiiiiiiii5------      ",
"      XXXXXXhhhhhhhhw+XXXXXiiiiiiiq;------      ",
"      XXXXXXhhhhhhp2OXXXXXXiiiiiiq>-------      ",
"      XXXXXXhhh&%#XXXXXXXXX59tt95;--------      ",
"      XXXXXXhhhXXXXXXXXXXXX---------------      ",
"      XXXXXXhhhXXXXXXXXXXXX---------------      ",
"      XXXXXXhhhXXXXXXXXXXXXiiiiiiiiiii----      ",
"      XXXXXXhhhXXXXXXXXXXXXiiiiiiiiiii----      ",
"      XXXXXXXXXXXXXXXXXXXXX---------------      ",
"      XXXXXXXXXXXXXXXXXXXXX---------------      ",
"      XXXXXXXXXXXXXXXXXXXXXiiiiiiiiiii----      ",
"      XXXXXXXXXXXXXXXXXXXXXiiiiiiiiiii----      ",
"      XXXXXXXXXXXXXXXXXXXXX---------------      ",
"      XXXXXXXXXXXXXXXXXXXXX---------------      ",
"      XXXXXXXXXXXXXXXXXXXXX--------------       ",
"          XXXXXXXXXXXXXXXXX                     ",
"               XXXXXXXXXXXX                     ",
"                     .XXXXX                     ",
"                          X                     ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "
]
