table=[
"48 48 156 2 ",
"   c None",
".  c black",
"X  c #6F6F6F",
"o  c #747474",
"O  c #777777",
"+  c #797979",
"@  c gray49",
"#  c #7E7E7E",
"$  c gray50",
"%  c #CB2D2E",
"&  c #C33536",
"*  c #A8724D",
"=  c #977C7C",
"-  c #A06D6E",
";  c #A37E6A",
":  c #EE6060",
">  c #578838",
",  c #71B043",
"<  c #778771",
"1  c #7A8C71",
"2  c #A78772",
"3  c #B89776",
"4  c #BC9970",
"5  c #8BA46F",
"6  c #92CA60",
"7  c #F5C567",
"8  c #F8C76B",
"9  c #A97F80",
"0  c #808080",
"q  c gray51",
"w  c #838383",
"e  c #848484",
"r  c #868686",
"t  c gray53",
"y  c #888888",
"u  c #898989",
"i  c gray54",
"p  c #8B8B8B",
"a  c gray55",
"s  c #8D8D8D",
"d  c #8E8E8E",
"f  c gray56",
"g  c #8A9881",
"h  c #8A9882",
"j  c #8A9088",
"k  c #909090",
"l  c gray57",
"z  c #929292",
"x  c #939393",
"c  c gray58",
"v  c #959595",
"b  c gray59",
"n  c #979797",
"m  c #9B9493",
"M  c #9A9696",
"N  c #989898",
"B  c #9B9B9B",
"V  c gray61",
"C  c #9D9D9C",
"Z  c #9D9D9D",
"A  c gray62",
"S  c #9F9F9F",
"D  c #A08B83",
"F  c #B78787",
"G  c #AA9191",
"H  c #A0A0A0",
"J  c gray63",
"K  c #A2A2A2",
"L  c gray64",
"P  c #A4A4A4",
"I  c #A5A5A5",
"U  c gray65",
"Y  c #A7A7A7",
"T  c #AEA5A3",
"R  c #ABA6A5",
"E  c #A9A6A6",
"W  c gray66",
"Q  c #A9A9A9",
"!  c #AAAAAA",
"~  c gray67",
"^  c #ACA8A8",
"/  c #ACACAC",
"(  c gray68",
")  c #AEAEAE",
"_  c #AFAFAF",
"`  c gray69",
"'  c #B1B1B1",
"]  c #B2B2B2",
"[  c gray70",
"{  c #B4B4B4",
"}  c gray71",
"|  c #B6B6B6",
" . c #B7B7B7",
".. c gray72",
"X. c #B9B9B9",
"o. c gray73",
"O. c #BBBBBB",
"+. c #BCBCBC",
"@. c gray74",
"#. c gray",
"$. c #C0C0C0",
"%. c gray76",
"&. c #C3C3C3",
"*. c gray78",
"=. c #C8C8C8",
"-. c gray79",
";. c #CBCBCB",
":. c gray80",
">. c #CDCDCD",
",. c gray81",
"<. c #D0D0D0",
"1. c gray82",
"2. c #D2D2D2",
"3. c LightGray",
"4. c gray83",
"5. c #D5D5D5",
"6. c gray84",
"7. c #D7D7D7",
"8. c #D8D8D8",
"9. c gray86",
"0. c gainsboro",
"q. c #DDDDDD",
"w. c gray87",
"e. c #DFDFDF",
"r. c gray88",
"t. c #E1E1E1",
"y. c #E2E2E2",
"u. c gray89",
"i. c #E4E4E4",
"p. c gray90",
"a. c #E6E6E6",
"s. c #E7E7E7",
"d. c gray91",
"f. c #E9E9E9",
"g. c #EAEAEA",
"h. c gray92",
"j. c #ECECEC",
"k. c gray93",
"l. c #EEEEEE",
"z. c #EFEFEF",
"x. c gray94",
"c. c #F1F1F1",
"v. c gray95",
"b. c #F3F3F3",
"n. c #F4F4F4",
"m. c gray96",
"M. c #F6F6F6",
"N. c gray97",
"B. c #F8F8F8",
"V. c #F9F9F9",
"C. c gray98",
"Z. c #FBFBFB",
"A. c gray99",
"S. c #FDFDFD",
"D. c #FEFEFE",
"F. c white",
"                                                                                                ",
"                                                                                                ",
"                        x M - = H H D 2 m H C 1 < S S S S S H H H H H H H H H H H H H H H t     ",
"                      n ^ & : % E ; 7 8 * _ > 6 , j _ _ _ _ _ _ _ _ _ ) ) ~ &.d.d.p.$.W ` z     ",
"                    u ] [ 9 F G _ T 4 3 R ( g 5 h ~ ! ! ! Q Q Q Q W W W W Q ' o...| ! Y W d     ",
"                    e Z S ~ [ [ [ ' W W W Y Y ~ o.o.X.} } } ] ] ] ] +.#.#.#. .' ' ' _ ( ! i     ",
"                  0 ;.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.D.M.7.5.5.3.1.<.,.>.:.%.Y U I P K K S 0     ",
"                  | F.F.F.F.F.F.F.F.F.F.F.F.F.F.D.S.A.Z.V.B.M.n.v.x.l.j.g.d.a.p.u.t.r.w.>.0     ",
"                0 g.F.F.F.F.F.F.F.F.F.F.F.F.F.D.S.Z.C.B.N.m.b.c.z.k.h.f.s.p.u.y.r.e.q.0.;.0     ",
"              0 %.F.F.F.F.F.F.F.F.F.F.F.F.D.S.A.C.V.N.m.b.v.x.l.j.g.d.a.i.y.t.e.w.q.0.9.;.0     ",
"              ! F.F.F.F.F.F.F.F.F.F.F.D.S.A.Z.V.B.M.n.v.x.l.j.g.d.a.p.i.u.u.u.y.u.u.u.a.4.0     ",
"            0 w.F.F.F.F.F.F.F.F.F.F.D.S.Z.C.B.N.M.n.b.v.c.x.z.z.k.l.k.j.h.g.f.d.d.d.d.d.6.0     ",
"          0 @.F.F.F.F.F.F.F.F.F.D.S.A.Z.Z.C.V.B.N.M.n.b.v.c.z.l.k.k.h.h.g.f.d.d.d.d.d.d.6.0     ",
"          A F.F.F.F.F.F.F.F.D.D.S.S.Z.C.V.B.N.M.n.b.v.c.z.z.l.k.j.h.g.f.d.d.d.d.d.d.d.d.6.0     ",
"        0 2.F.F.F.F.F.F.F.D.D.S.A.C.C.V.B.N.m.n.b.v.x.z.l.k.j.h.g.f.d.d.d.d.d.d.d.d.d.d.6.0     ",
"      e H Q I / Q I ] ....*.8.7.t.V.B.N.M.n.b.v.c.z.l.k.k.h.h.g.f.d.d.d.d.d.d.d.d.d.d.d.6.0     ",
"      Z [ [ [ { { } } } ......O...] ` / Q I J P K S W ` ) X.-.=.2.d.d.d.d.d.d.d.d.d.d.d.6.0     ",
"    a _ ) ) _ _ ` ` ' ' ' ] ] [ [ { { { } } } | | |  ...X.X.O.+.] ' ` K U L n H H b U ( K 0     ",
"  q Q Q Q Q Q Q ! ~ ~ ~ / ( ( ) ) _ _ ` ` ' ' ] ] ] [ [ { { { } } } | | |  . . . ...X.o...d     ",
"  w A J P L L P P I I U U Y Y W W Q Q ! ! ~ ~ / ( ( ) ) _ _ ` ` ' ' ] ] ] [ [ { { { } } } l     ",
"  0 u e e e p i l k b v B Z H K K L L P P I I U U Y Y W Q Q ! ! ~ ~ / ( ( ) ) _ _ ` B o [ k     ",
"        0 0 0 0 0 0 w r r y t y p d f z z b N V A J J K K L L P P I U U Y Y W Q S + X O ) d     ",
"                              $ $ $ 0 0 0 i u s i i u d d l z c b B B A H J J H t l t q Q a     ",
"                                                  @ # # $ 0 0 w i y i t y p s f k x b b k 0     ",
"                                                                        @ @ # $ 0 0 e e 0       ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                        . . . . . . . . . . . . . . . . . . . . . . . . . . .                   ",
"                    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .                 ",
"                    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .                 ",
"                  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .                 ",
"                . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .                 ",
"                . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .                 ",
"                      . . . . . . . . . . . . . . . . . . . . . . . . . . . . .                 ",
"                                      . . . . . . . . . . . . . . . . . . . . .                 ",
"                                                    . . . . . . . . . . . . . .                 ",
"                                                                    . . . . . .                 ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
]