table=[
"48 48 150 2 ",
"   c None",
".  c #1A1304",
"X  c #2E2207",
"o  c #3F320D",
"O  c #392F1A",
"+  c #3C3017",
"@  c #4A3B16",
"#  c #40361B",
"$  c #544314",
"%  c #65531D",
"&  c #5D5030",
"*  c #735F20",
"=  c #6A5C39",
"-  c #776738",
";  c #79683E",
":  c #756741",
">  c #876C26",
",  c #886E23",
"<  c #947B2C",
"1  c #816C35",
"2  c #897230",
"3  c #87784F",
"4  c #82734B",
"5  c #897C56",
"6  c #9D802A",
"7  c #A38A34",
"8  c #B0913E",
"9  c #BE9F3C",
"0  c #91835A",
"q  c #A18C4B",
"w  c #A48F58",
"e  c #A9965C",
"r  c #B19B52",
"t  c #B19C5A",
"y  c #BEA34C",
"u  c #9D8F64",
"i  c #A79765",
"p  c #AA9962",
"a  c #A4966A",
"s  c #AB9C6C",
"d  c #B9A670",
"f  c #C3A643",
"g  c #C7AB49",
"h  c #C8AD55",
"j  c #CDB351",
"k  c #D5BA50",
"l  c #D3BD5A",
"z  c #CFBA63",
"x  c #CFBD6C",
"c  c #D3BD64",
"v  c #CDBE74",
"b  c #C2B17B",
"n  c #CCBD7E",
"m  c #D1BD74",
"M  c #DCC35D",
"N  c #E7CA57",
"B  c #E1C65C",
"V  c #E5CA5D",
"C  c #F3D45B",
"Z  c #D7C067",
"A  c #D9C262",
"S  c #D4C16D",
"D  c #D4C374",
"F  c #D7C876",
"G  c #D8C877",
"H  c #D2C27D",
"J  c #DBCB7C",
"K  c #DFD17F",
"L  c #E7CC62",
"P  c #E9CE61",
"I  c #EBD262",
"U  c #EFD56B",
"Y  c #F1D667",
"T  c #F5DB6C",
"R  c #EAD575",
"E  c #E3D47F",
"W  c #EEDB7E",
"Q  c #EAD57C",
"!  c #F0D972",
"~  c #F0DA79",
"^  c #FAE274",
"/  c #FBE57A",
"(  c #FDE87E",
")  c #BCAF80",
"_  c #CCBA82",
"`  c #CCBE8A",
"'  c #D0BD82",
"]  c #CDC184",
"[  c #CEC38C",
"{  c #D4C484",
"}  c #DDCD85",
"|  c #D3C48B",
" . c #DAC688",
".. c #DACD89",
"X. c #DDD18C",
"o. c #CCC392",
"O. c #CDC89B",
"+. c #DACD96",
"@. c #D6CB99",
"#. c #DACF9C",
"$. c #DED393",
"%. c #DDD39B",
"&. c #DFD89F",
"*. c #E1CF88",
"=. c #E7D380",
"-. c #ECDC84",
";. c #E3D48D",
":. c #EBDA8C",
">. c #F2DF85",
",. c #E1CE90",
"<. c #E4D693",
"1. c #E8D596",
"2. c #EADD9B",
"3. c #F3E287",
"4. c #FDE984",
"5. c #F5E58B",
"6. c #F8E789",
"7. c #FDEC8D",
"8. c #F4E493",
"9. c #FDED94",
"0. c #F3E79B",
"q. c #FCEE9B",
"w. c #CDC9A2",
"e. c #CFCDA8",
"r. c #DFD5A2",
"t. c #DDD5A8",
"y. c #E1D6A0",
"u. c #E0DAA4",
"i. c #E9DDA3",
"p. c #E2DCAC",
"a. c #EBE2AB",
"s. c #F5EBA4",
"d. c #FBEFA3",
"f. c #F5ECAA",
"g. c #FAEFA9",
"h. c #FBF0A6",
"j. c #FAF0AC",
"k. c #E5E1B4",
"l. c #E8E3B6",
"z. c #E3E1B8",
"x. c #EFE9B9",
"c. c #F3EBB5",
"v. c #F3EDBB",
"b. c #F9F1B4",
"n. c #F7F2BE",
"m. c #F8F2BB",
"M. c #F3EEC0",
"N. c #F7F3C4",
"B. c #F8F4C2",
"V. c #F7F4C9",
"                                                                                                ",
"                                                      w +.v.n.                                  ",
"                                                  ,.v.B.B.B.n.y.                                ",
"                                            1.N.N.B.B.B.B.n.n.n.p                               ",
"                                      o.v.N.N.B.B.B.n.n.n.n.m.m.c.                              ",
"                                [ v.V.N.N.B.B.B.B.n.n.n.n.m.m.m.m.n                             ",
"                           .x.N.N.N.N.N.B.B.B.n.n.n.n.m.m.m.m.b.m.b.                            ",
"                    _ c.V.V.V.V.N.N.N.N.B.B.n.n.n.n.m.m.m.m.b.b.b.b.<.                          ",
"              _ x.V.V.V.V.V.V.V.B.B.B.B.B.B.m.m.m.m.m.m.m.m.b.b.b.b.j.t                         ",
"              v.V.N.V.V.N.N.B.B.B.B.B.B.m.m.m.m.m.m.m.b.b.m.b.b.b.b.j.d.                        ",
"              s V.V.N.N.B.B.B.B.B.m.m.B.m.m.m.m.b.b.m.b.b.b.j.b.b.b.j.j.m                       ",
"                c.V.N.N.B.B.B.n.B.m.m.m.m.m.m.m.b.m.b.b.b.b.b.j.j.j.j.j.j.1                     ",
"                i N.B.B.B.B.n.n.m.m.m.m.b.b.b.m.b.b.b.b.j.b.j.b.j.j.j.j.j.:.                    ",
"                e c.B.B.n.n.n.n.m.m.m.m.b.b.b.b.b.b.b.b.j.j.j.j.j.j.j.h.g.g.r                   ",
"            { v.e.<.n.B.n.n.m.m.m.m.m.m.b.b.b.b.b.b.j.j.j.j.j.j.j.g.g.g.g.d.q.                  ",
"         .N.V.V.z.o.f.n.n.m.m.m.b.m.m.m.b.b.b.b.b.b.b.j.j.j.j.j.h.g.h.h.d.h.d.S                 ",
"    [ N.V.V.V.V.N.w.;.b.m.m.m.b.b.b.b.b.b.b.j.b.j.j.j.j.j.j.h.h.g.g.h.h.d.d.d.q.2               ",
"] V.V.V.V.V.N.N.N.k.[ f.m.b.m.b.b.b.b.b.b.b.j.j.b.j.j.j.h.j.h.h.g.d.h.h.q.d.d.q.W               ",
"; N.V.N.V.N.N.N.N.n.O.;.m.b.m.b.b.b.b.b.j.j.j.j.j.j.j.h.h.h.h.h.d.d.d.d.q.q.q.q.q.y             ",
"  d V.N.N.N.N.N.n.n.p.] h.b.b.b.b.b.b.j.j.j.j.j.j.j.h.h.h.h.h.h.d.d.q.d.q.d.q.q.q.7.            ",
"8 j f.V.N.n.N.n.n.n.n.O.E j.b.b.j.j.b.j.j.j.j.j.f.h.h.h.h.h.d.d.d.q.d.q.q.q.q.q.q.9.M           ",
"<.I A N.N.n.n.n.n.m.m.u.H 0.b.j.b.j.b.j.j.h.j.h.h.h.h.h.h.d.d.d.d.q.q.q.q.q.q.q.q.9.7.<         ",
"  $.M } n.n.m.m.m.m.m.m.o.E b.j.j.j.j.j.h.j.h.h.h.h.h.d.d.d.q.q.q.q.q.q.0.q.9.9.9.9.9.!         ",
"    2.M a.m.m.m.m.m.m.m.u.D q.j.j.h.h.h.h.h.h.h.d.d.h.d.q.d.q.q.q.q.q.q.q.9.9.9.9.9.9.7.f       ",
"    & 2.A n.m.m.b.m.m.b.f.o.R h.j.h.h.h.h.h.s.s.d.d.d.q.q.d.q.q.q.q.9.q.9.9.9.9.9.9.9.7.4.      ",
"      : $.J n.b.b.b.b.b.b.&.D 9.h.h.h.h.s.s.d.d.d.q.d.q.q.q.q.q.q.q.9.9.9.9.9.9.9.7.7.7.7.B     ",
"        3 ..a.b.b.b.b.b.j.f.[ U h.h.d.d.d.d.d.q.q.d.q.q.q.q.q.q.9.9.9.9.9.9.9.9.7.7.7.7.7.4.6   ",
"          0 { c.b.b.b.b.j.b.&.S 7.s.d.d.d.d.d.d.q.q.q.q.q.q.q.9.9.9.9.9.9.9.7.7.7.7.7.7./ g $   ",
"            u $.m.j.j.j.j.j.s.] ! q.h.q.d.d.q.q.q.q.q.q.9.9.9.9.9.9.7.7.9.7.7.7.7.7./ N 6       ",
"              a p.b.j.j.j.j.h.$.S 7.d.d.q.q.q.q.q.q.9.q.9.9.9.9.9.9.7.9.7.7.7.7.^ V g %         ",
"                i x.j.j.h.f.h.s.] I q.q.q.q.q.0.q.9.q.9.9.9.9.9.9.9.9.7.7.4.^ V z F R ,         ",
"                  d m.j.h.h.h.h.$.S 7.q.q.q.q.q.9.9.9.9.9.9.9.5.7.7.7.4.! B c F W T 7           ",
"                    _ b.h.h.h.h.0.n U q.q.q.q.9.q.9.9.9.9.7.7.7.7.7.Y M x G 3./ y o             ",
"                      r.h.h.h.q.d.X.Z 6.9.9.9.9.9.9.9.9.9.7.7.4.T M x K 6.( k $                 ",
"                        c.h.q.d.q.0.v Y 9.9.9.9.9.9.7.7.7.4.U M S E 6.4.V *                     ",
"                        s j.q.q.q.q.X.A 4.9.9.9.9.7.7.4.I M S E 6.4.T < .                       ",
"                          @.h.q.q.q.8.v Y 9.9.9.7./ I A F -.7.7./ 9 X                           ",
"                            c.q.q.q.9.} M 4.7./ V Z F -.7.6.4.L >                               ",
"                            0 j.q.9.9.5.x C V c J 3.7.7.7.W h @                                 ",
"                              o.h.9.9.9.J x } 5.7.7.7.-.G q .                                   ",
"                                a.q.9.9.5.5.7.7.7.8.*.{ -                                       ",
"                                4 g.9.7.7.7.7.q.;.%.| #                                         ",
"                                  ) q.7.7.q.2.@.l.i                                             ",
"                                    a.d.2.%.z.k.=                                               ",
"                                    = 5 + t.o.O                                                 ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
]